Refactor Using JS Classes
damdafayton/awesome-books pull request #3
Opened 2022-02-08 15:14 UTC by AyoubMs

In this Milestone, we:
- Refactored the Code from Arrays and Objects to Classes
- Styled the layout
- Fixed the bugs that comes from refactoring

2022-02-08 16:25 UTC, Cathella requested changes
## ⚠️ Status: Changes Required 🛑

### Hi @AyoubMs 👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## To Highlight 👏🏻

✅ No linter errors.
✅ You used correct Github Flow.
✅ It uses JavaScript classes and methods

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 16:25 UTC, Cathella commented on index.html
>      <title>Document</title>
Hello @AyoubMs, your project looks good. I like the way your code is structured ❤️. However I am going to suggest some changes to make it look better 👀.

- [ ] [OPTIONAL] It would be nice if the title of the project relates to the project you are working on - "Awesome Books" would still look great!

2022-02-08 16:25 UTC, Cathella commented on js/script.js
> +  }
✔️ This `addNewBook()` class method does a great job! 🔥

2022-02-08 16:25 UTC, Cathella commented on js/script.js
> +  }
This method is well structured but it does not work as intended. Please refactor the code where you call this method and make sure that only one item is removed at a time. See the unintended behavior below 👇🏻 

![books](https://user-images.githubusercontent.com/4247740/153030431-85dc6994-6b62-4eee-9f04-cda99eac34d0.gif)

2022-02-08 17:44 UTC, damdafayton commented on js/script.js
> +  }
@AyoubMs hi,
The equality supposed to be !==
Morning peers already warned about this today

2022-02-09 09:07 UTC, medaminedev66 approved these changes
Hi @AyoubMs and @ayubch, 

## Status: Approved

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 09:34 UTC, merged